### PR TITLE
Enhancing compatibility of Python objects representing Kubernetes resources 

### PR DESCRIPTION
**Pull request by landerlini**
# Summary

Python objects representing Kubernetes resources MUST identify the optional fields as such and use the same default values as for the official Kubernetes APIs. Otherwise the behavior of the resource with unspecified fields will differ in concrete and virtual nodes. 

In this PR, we enhance these Resource Models. 

Explicit dependence on the Kubernetes Python client may enhance consistency and maintainability, but may increase the complexity in the integration. It should be evaluated for a future major change.

In progress:
 - [x] complete testing
 - [x] update the example changing GET to POST method where needed
 - [x] regenerate openapi.json

### CODE REVIEW

**Comment by dciangot** [comment]
agree on the k8s binding element, although I think we can kind of survive with the current subset of resources. 

Is there any particular reason for this PR to be a draft though?

otherwise I think you can go ahead, but remember to generate a new openapi spec file to be put here: https://github.com/interTwin-eu/interLink/blob/main/docs/openapi/openapi.json

**Comment by dciangot** [comment]
also, can you add the changes related the log API now being a get instead of a POST?

**Comment by landerlini** [comment]
Ciao Diego, PR is in draft mode because I am not done with testing. 
Ok for modifying the docs and the example.

**Comment by landerlini** [comment]
> remember to generate a new openapi spec file to be put here: https://github.com/interTwin-eu/interLink/blob/main/docs/openapi/openapi.json

It seems the "main" package was not committed in the repo, which breaks "create_openapi.py" to generate the json schema.
I fixed create_openapi.py to be self-contained, and used it to generate the json schema.

**Review by dciangot — APPROVED** [review]
LGTM

**Pull request merged**
