### PR TITLE
Hotfix/issue259 refreshtoken not reused

### LINKED ISSUE #259: Refresh token not reused
Refresh token should be renewed and reused to get new tokens. Instead, currently, it uses the first token provided by ENV, which will then expire in 15min.

Correction: quite simple, put the read code of the token inside the while loop: https://github.com/interTwin-eu/interLink/blob/main/docker/scripts/refresh.py#L30

If I have the time, I might do a pull request.

Symptoms:
```
response {'error': 'bad_refresh_token', 'error_description': 'The refresh token passed is incorrect or expired.', 'error_uri': 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code'}
```

Fix:
```
    try:
        with open(output_file+"-refresh", "r") as text_file:
            rt = text_file.readline()
        if rt != "": 
            iam_refresh_token = rt
    except:
        logging.info("No cache for refresh token, starting from ENV value")

    print(iam_refresh_token)
    token = None

    while True:
```
to

```
    while True:
        try:
            with open(output_file+"-refresh", "r") as text_file:
                rt = text_file.readline()
            if rt != "": 
                iam_refresh_token = rt
        except:
            logging.info("No cache for refresh token, starting from ENV value")
    
        print(iam_refresh_token)
        token = None

```

### PR DESCRIPTION
**Pull request by antoinetran**
# Summary

Fix https://github.com/interTwin-eu/interLink/issues/259 and some debug log added
---

**Related issue :**
#259

### CODE REVIEW

**Review by dciangot — APPROVED** [review]
LGTM! Thanks @antoinetran

**Comment by dciangot** [comment]
I'll run integration tests locally, since we are experiencing false negative through gh actions. Once checked I'll merge this

**Comment by antoinetran** [comment]
For info, this is the new debug info, plus the response info in case of error, because it is a good info to know it fails because of expiration:
```
INFO:__main__:Verbose mode: setting log to debug.
INFO:__main__:No cache for refresh token, starting from ENV value
INFO:__main__:Current refresh token: REDACTED
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "POST /login/oauth/access_token HTTP/11" 200 None
DEBUG:__main__:{'error': 'bad_refresh_token', 'error_description': 'The refresh token passed is incorrect or expired.', 'error_uri': 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code'}
DEBUG:__main__:iam_client_id REDACTED iam_client_secret REDACTED response {'error': 'bad_refresh_token', 'error_description': 'The refresh token passed is incorrect or expired.', 'error_uri': 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code'}
WARNING:__main__:ERROR oidc get token: 'access_token'
Traceback (most recent call last):
  File "/opt/refresh.py", line 124, in <module>
    token = response['access_token']
KeyError: 'access_token'
WARNING:__main__:Response if available: {'error': 'bad_refresh_token', 'error_description': 'The refresh token passed is incorrect or expired.', 'error_uri': 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code'}
```

**Comment by dciangot** [comment]
I confirm, this is good to go

**Pull request merged**
