### PR TITLE
Python scripts code refactor

### PR DESCRIPTION
**Pull request by Surax98**
And OpenAPI update

# Summary

Refactored variables and functions name in python scripts to match snake_case (for variables and functions) and CamelCase for classes.
Also, update the openAPI script to generate OpenAPI JSON file. It is now compliant with the current version (it will be updated in the future to match v0.4.x and newer versions).

**Related issue :**
#250 #253

### CODE REVIEW

**Comment by Surax98** [comment]
LGTM

**Comment by dciangot** [comment]
Since we are here, @Surax98 what about a github action that build the json spec and store it as a release artifact?

So then we can point the documentation to the latest build artifact.

**Comment by Surax98** [comment]
> Since we are here, @Surax98 what about a github action that build the json spec and store it as a release artifact?
> 
> So then we can point the documentation to the latest build artifact.

Sure thing. Same PR or another one?

**Comment by dciangot** [comment]
Another one, thanks

**Comment by Surax98** [comment]
> Another one, thanks

Ok, no problem. Would it be ok to actually execute the script upon every push and directly in-place commit and push the generated JSON? Basically, to update the file and replace the old one.

**Comment by dciangot** [comment]
no automatic commits, I'd put the json as a release artifact (meaning, the exact position of the binaries), and then doc will take the reference from the public endpoint of the release.

**Review by dciangot — APPROVED** [review]
LgTM

**Pull request merged**
