### PR TITLE
updated oauth2 proxy startup script inside installer with the correct…

### LINKED ISSUE #190: Set default good tls cipher for OAuth2
# Short Description of the issue

To be set here https://github.com/interTwin-eu/interLink/blob/main/cmd/installer/templates/interlink-install.sh#L99
Security scans recommend the followings atm:

```
        --tls-cipher-suite=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA \
        --tls-cipher-suite=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA \
        --tls-cipher-suite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 \
        --tls-cipher-suite=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA \
        --tls-cipher-suite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 \
        --tls-cipher-suite=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256  \
        --tls-cipher-suite=TLS_RSA_WITH_AES_128_CBC_SHA \
        --tls-cipher-suite=TLS_RSA_WITH_AES_128_GCM_SHA256 \
        --tls-cipher-suite=TLS_RSA_WITH_AES_256_CBC_SHA \
        --tls-cipher-suite=TLS_RSA_WITH_AES_256_GCM_SHA384 \
        --tls-cipher-suite= TLS_AKE_WITH_AES_128_GCM_SHA256 \
```

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

### PR DESCRIPTION
**Pull request by Bianco95**
# Summary

updated oauth2 proxy startup script inside installer with the correct tls cipher flags to be compliant with security protocols

### CODE REVIEW

**Review by dciangot — APPROVED** [review]
LGTM

**Review by dciangot — COMMENTED** [review]
@Bianco95 do you know if a single option with values comma-separated can work in the same way? it would be cleaner

**Comment by dciangot** [comment]
> @Bianco95 do you know if a single option with values comma-separated can work in the same way? it would be cleaner

@Bianco95  any news on this?

**Comment by Bianco95** [comment]
> > @Bianco95 do you know if a single option with values comma-separated can work in the same way? it would be cleaner
> 
> @Bianco95 any news on this?

Yes, this option with comma-separated value works as expected 
```shell
--tls-cipher-suite=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384 \
```

**Pull request merged**
